1 name: test
2 on: push
3 jobs:
4   test:
5     runs-on: ubuntu-22.04
6     container: ryuichiueda/ubuntu22.04-ros2:latest
7     steps:
8       - uses: actions/checkout@v2
9       - name: build and test
10        run: |
11          rsync -av ./ /root/ros2_ws/src/mypkg/
12          cd /root/ros2_ws
13          rosdep update
14          rosdep install -i --from-path src --rosdistro humble -y
15          bash -xv ./src/mypkg/test/test.bash /root
